### ISSUE TITLE
Query about layout

### ISSUE THREAD

**Issue by phgeller** [newtheatre/history-project#11]
interesting that this still appears:

![image](https://cloud.githubusercontent.com/assets/11944184/7142209/c510cdec-e2ce-11e4-855b-2bb949888edc.png)

even though its not in the code:

![image](https://cloud.githubusercontent.com/assets/11944184/7142219/df911cd0-e2ce-11e4-88fb-45b9f7ab10d2.png)

**Comment by phgeller** [comment]
Im talking specifically about the word "IMAGES"

**Comment by wjdp** [comment]
Yeah I've not put a bit in that checks if there are images or not. I'll leave this for now and sort it out when we settle on an photo/publicity thing #10.

**Comment by phgeller** [comment]
so is the word "images" part of the default page layout?

**Comment by wjdp** [comment]
It's part of the single show page yeah

**Comment by phgeller** [comment]
ok cool!

*------------------*
*Philip Geller*

*M: 07754 056896*
*E:  Philip.Geller@gmail.com <Philip.Geller@gmail.com>*
*W: www.philgeller.co.uk <http://www.philgeller.co.uk>*
