### ISSUE TITLE
Collect cast / crew lists 2013-14

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#110]
Google spreadsheet for role and names, cast crew division?

**Comment by wjdp** [comment]
https://docs.google.com/spreadsheets/d/10T2ITqWAnO6bgMeNs-Hq3lmFVqZJQ6Re1OvoYMSHCq8/edit?usp=sharing

**Comment by wjdp** [comment]
Spreadsheet now closed, additional details should go through main contributing channels

**Comment by wjdp** [comment]
- **Freshers Fringe** cast and directors
- **Pitchfork** cast roles
- **Conviction** cast and crew incomplete
- **Judas** no cast
- **Letting Go** cast and crew incomplete
- **Blue Remembered Hills** cast incomplete, few crew
- **The Rehersal** no cast
- **Cracked China** no cast or crew
- **R&J** no cast
- **Customs** no cast or crew
- **Equus** no cast
- **That Face** no cast, short crew list
- **Servant** no cast

**Comment by wjdp** [comment]
Suitable amount done for launch, moving to update-1

**Comment by nhyty** [comment]
Have added Judas, The Rehearsal and Servat, can't fine That Face info as not on facebook event.

**Comment by nhyty** [comment]
Have now added That Face

**Comment by nhyty** [comment]
Have also done kiss me list

**Comment by wjdp** [comment]
Just FF left
