### ISSUE TITLE
download 8 photos per show for 2013-2014

### ISSUE THREAD

**Issue by phgeller** [newtheatre/history-project#111]

**Comment by wjdp** [comment]
Autumn now done, couldn't find any for:

- Freshers Fringe
- Vessel (probs not any)
- Sorry Wrong Number
- God of Carnage
- Back To Oblivion
- Buried Child
- CLEAN

**Comment by wjdp** [comment]
Spring done, couldn't find any for quite a few. Will have to source from elsewhere. Bulk job done so issue closed
