### ISSUE TITLE
Some more famous alumni

### ISSUE THREAD

**Issue by nhyty** [newtheatre/history-project#1159]
This is some info about 3 alumni from the 90s and a tv show they created and won a bafta for

http://www.adrenalini.com/#!about-adrenalini-brothers/
https://web.archive.org/web/20070228123313/http://www.newtheatre.org.uk:80/alumni.php

**Comment by samozzy** [comment]
**Owen Phillips** is also referenced in the old NT website link, but we have no information on him. Probably someone to investigate!
