### ISSUE TITLE
Character limit on person roles 

### ISSUE THREAD

**Issue by samozzy** [newtheatre/history-project#1184]
On the person page, one role can fall into another if it's reeeeeaaaaallly long 
![image](https://user-images.githubusercontent.com/15388319/41173107-b07ed6de-6b4d-11e8-9bfb-29f2751556af.png)

**Comment by wjdp** [comment]
@samozzy This is likely because there aren't spaces between the slashes so the browser doesn't know how to line wrap

**Comment by samozzy** [comment]
Preventative measure put in place with #1219
