### ISSUE TITLE
Bio Submission Alumni Network Registration 

### ISSUE THREAD

**Issue by samozzy** [newtheatre/history-project#1216]
It is possible that people who submit a bio are not on the alumni network. If so, and they tick that we can contact them, we have no way of contacting them... 

Where is the best place to put the link to signup for the alumni network? [This Google Form](https://docs.google.com/forms/d/e/1FAIpQLSdpa5pg2Ypp6LXyYPS7AFivreHymY_W5Noa3J-VbIrfKrNHYw/viewform?embedded=true)

**Comment by nhyty** [comment]
its already on the person collect form...

**Comment by samozzy** [comment]
Sam is blind.

**Comment by nhyty** [comment]
@samozzy indeed
