### ISSUE TITLE
StuFF Management

### ISSUE THREAD

**Issue by samozzy** [newtheatre/history-project#1218]
This year, we had a structured management team for StuFF to run the festival through the weekend.
- Should we record this?
- How?

A solution that comes to mind is having a show called 'StuFF' with the poster, some details, etc. Can also include the StuFF festival gallery here as production shots.
However, I'm aware that this isn't a show so is there a better way?

**Comment by BenWoodford76** [comment]
I like this idea :)

**Comment by GingertronMk1** [comment]
@BenWoodford76 Would there be a way of having stuff roles displayed similar to how committee is displayed on the year page?

**Comment by samozzy** [comment]
@GingertronMk1 This would be fairly trivial, as we could just add them to the committee file for the year. The downside is that it doesn't provide a way to show the photos (or other relevant content).

**Comment by samozzy** [comment]
# StuFF 2018 Management
Duty Manager: Callum Walker
Duty Assistant: Daniel McVey
Duty Front of House Manager: James Curling
Venue Manager: Ben Woodford
Assistant Venue Manager: Ian Webster
Venue Manager: Sam Osborne
Assistant Venue Manager: Zoe Smith

# StuFF 2017 Management
Duty Manager: Chris Trueman
Venue Manager: Nathan Penney
(@nhyty - anyone else?)

**Comment by nhyty** [comment]
@samozzy Err, not really, Niamh was dep duty manager probs

**Comment by samozzy** [comment]
@BenWoodford76 Did you get around to this? Can make it as a show file this week if not
