### ISSUE TITLE
Best Practice guide for crew lists

### ISSUE THREAD

**Issue by BenWoodford76** [newtheatre/history-project#1230]
Does what it says on the tin,

should probably add to the contributors/editing guide.

what do we think the order should be?

my thoughts:

Director
Producer
assistants/shadows where applicable
Tech director & Shadow
Designers (LX, Sound, Set etc.)
any special technical roles for that show
Costume/make up people
Tech Operators
Stage Managers

What are people's thoughts??

**Comment by GingertronMk1** [comment]
@BenWoodford76 Good idea, maybe extend it to include ordering of everything in a show file, like links and photos

**Comment by BenWoodford76** [comment]
any further thoughts on the ordering of this? If people are happy with the order I'll add it to the skeleton file
