### ISSUE TITLE
Find posters for 2011-12

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#125]
Quite a few are missing, some Facebook scouring I think!

**Comment by nhyty** [comment]
![the hothouse](https://cloud.githubusercontent.com/assets/14825903/10538916/c9be92dc-73f3-11e5-8253-269b4bdb52cd.jpg)
This is the last one that i can see being needed.

**Comment by wjdp** [comment]
Is quite low resolution, could you see a copy that's any bigger?

**Comment by nhyty** [comment]
not really, i only found it from the only cast member i know's facebook

**Comment by wjdp** [comment]
Ah well, thanks though
