### ISSUE TITLE
Unscripted as a season

### ISSUE THREAD

**Issue by samozzy** [newtheatre/history-project#1261]
The theatre is currently advertising Unscripted as a season rather than an external slot. This should be reflected in the archive. 
- Do we change them retrospectively?

**Comment by GingertronMk1** [comment]
I'm inclined to say don't change retrospectively; uncut shows are still called as such, but from here on out `season: Unscripted`

**Comment by samozzy** [comment]
Current status: Being pressed on making this its own season for this academic year.

**Comment by nhyty** [comment]
closed in #1391

**Comment by wjdp** [comment]
Is 'Unscripted' the continuation of 'UNCUT' → 'Fringe' or it's own thing? If this is a replacement for 'Fringe' I would be in favour of merging them the same way we did for UNCUT/Fringe. (See https://history.newtheatre.org.uk/seasons/fringe/)

**Comment by BenWoodford76** [comment]
@wjdp Is a new thing

**Comment by BenWoodford76** [comment]
@BenWoodford76 Unauditioned troupe
