### ISSUE TITLE
Create some help pages

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#13]
Help pages should document things like the attribute tags we're deciding on here for quick reference.

**Comment by phgeller** [comment]
To clarify do you mean things like:

"notes" means a comment in brackets. This is to be used in committee
listings to denote, for example, a committee position which was split
between two people across the year.

*------------------*
*Philip Geller*

*M: 07754 056896*
*E:  Philip.Geller@gmail.com <Philip.Geller@gmail.com>*
*W: www.philgeller.co.uk <http://www.philgeller.co.uk>*

**Comment by wjdp** [comment]
Yes, also used for things on show pages, as in the Mercury fur page where
some crew were changed for NSDF

On Tue, Apr 14, 2015 at 9:33 PM, phgeller <notifications@github.com> wrote:

> To clarify do you mean things like:
>
> "notes" means a comment in brackets. This is to be used in committee
> listings to denote, for example, a committee position which was split
> between two people across the year.
>
> *------------------*
> *Philip Geller*
>
> *M: 07754 056896*
> *E: Philip.Geller@gmail.com <Philip.Geller@gmail.com>*
> *W: www.philgeller.co.uk <http://www.philgeller.co.uk>*
>
> On Tue, Apr 14, 2015 at 7:40 PM, Will Pimblett <notifications@github.com>
> wrote:
>
> > Help pages should document things like the attribute tags we're deciding
> > on here for quick reference.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/newtheatre/history-project/issues/13>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newtheatre/history-project/issues/13#issuecomment-93051078>
> .
>



-- 
Will
Full AF | Online Media Done Right
http://*fullaf*.com <http://fullaf.com/> | 07812801550
