### ISSUE TITLE
Customs poster low resolution

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#136]
http://history.newtheatre.org.uk/shows/13_14/customs.html

Poster width is below the minimum of 440px (the used maximum size on the site). A better quality file is wanted.

Currently there is no prescribed minimum size for master images to be, touched briefly in #51 when collecting images they should be acquired in the highest res possible while being below a sensible max of ~1500px.

**Comment by nhyty** [comment]
Merged into this issue #336
