### ISSUE TITLE
People section, alumni bios etc

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#14]
I would imagine users would like to look up their contemporaries. A record could show what shows they were involved in during their time and additional information such as a bio/awards/what they're up to now.

@phgeller This 'feature' really adds to the scope of the project, I don't think it should be added straight away.

**Comment by wjdp** [comment]
Discussed, we need to draw up a list of stuff to have in bio

- Full Name
- Year Graduated
- Commendation/Fellowship (a cool icon to go with this, like a medal or something)
- Job now
- Name of drama school (if applic.)
- Freeform text bio with headings and pictures

**Comment by phgeller** [comment]
We would really like to start collecting a set of alumni biographies to be displayed here on the alumni website. We have so many alumni who are now well-established in the industry, and we are hoping to help the current students to bridge the gap between the world of student productions and that of professional theatre. 

If you would be interested in publishing an alumni bio on the website then please get in touch via alumni@newtheatre.org.uk. We are keen to publish bios for all alumni who are interested, irrespective of whether you are currently working in theatre or not. We would be looking to publish the following details:

Name
Year of Graduation
Interests/roles while at the New Theatre
Current Job/Industry Placement
Drama School Attended (Where applicable)
Any advice for current students 
Contact Details (ONLY if you are willing to be contacted by current students)

We are looking forward to publishing the first alumni profiles in the near future.

**Comment by wjdp** [comment]
Is a thing, has been a thing for a while
