### ISSUE TITLE
Warehouse 364 poster low resolution

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#140]
http://history.newtheatre.org.uk/shows/08_09/warehouse_364.html

Poster width is below the minimum of 440px (the used maximum size on the site). A better quality file is wanted.

Currently there is no prescribed minimum size for master images to be, touched briefly in #51 when collecting images they should be acquired in the highest res possible while being below a sensible max of ~1500px.

**Comment by nhyty** [comment]
Closed and merged into issue #336
