### ISSUE TITLE
Discuss, decide and set a licence for the content on the site

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#145]
We are slowly garnering a growing collection of textual and image content. Others may want to use the stuff we have. Should they be able to? and under what terms?

**Comment by wjdp** [comment]
My vote is for an open licence which allows others to use, change and distribute the site's content as long as attribution is made and the derived work is released under the same or a compatible licence. Commercial use of the work is not allowed.

Any of the above conditions can be waived with the permission of the copyright holder. (Us, theatre committee?)

<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.

**Comment by nhyty** [comment]
This makes sense to me, as long as it is noted that it is NNT stuff I see no problem.

**Comment by nhyty** [comment]
Shall we implement this now

**Comment by wjdp** [comment]
at some point before the dinner yes

**Comment by wjdp** [comment]
Rather than declaring a licence and locking ourselves into to something I'm going to leave this for now. We can revisit if it comes up.
