### ISSUE TITLE
Collect cast / crew lists 2014-15

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#149]
Akin to #110, get a spreadsheet going and send round to relevant people

**Comment by nhyty** [comment]
working on it

**Comment by nhyty** [comment]
This is the in-house autumn season list https://docs.google.com/spreadsheets/d/1jYXCgfGbPti6qTeS-0wmiyyuhOPi6V5onZ7jX4ojrus/edit#gid=846586954

**Comment by nhyty** [comment]
All in house and fringe shows are in google sheets, will has access to all of them

**Comment by wjdp** [comment]
Awesome! :octopus: 

Will process these within the next week.

**Comment by wjdp** [comment]
@nhyty Have done the import, can you have a flick through at some point and to find all my mistakes?

**Comment by nhyty** [comment]
will do
