### ISSUE TITLE
/people/presidents

### ISSUE THREAD

**Issue by samozzy** [newtheatre/history-project#1500]
List all presidents with their year, including unknown presidents.
At the request of @phgeller

**Comment by wjdp** [comment]
See https://history.newtheatre.org.uk/people/fellows/ for an example

**Comment by phgeller** [comment]
Good evening everyone - is anyone able to have a look at this for me? IT would be great it if I could make some progres with this over December. 

(sorry to pester)

**Comment by BenWoodford76** [comment]
@samozzy I remember you saying you’d have a look at this, any progress? 😁

**Comment by samozzy** [comment]
@BenWoodford76 Currently confused by ruby and doing other work so not really sadly!
