### ISSUE TITLE
Change name from "New Theatre" to "Nottingham New Theatre"

### ISSUE THREAD

**Issue by phgeller** [newtheatre/history-project#160]

**Comment by phgeller** [comment]
Change all instance where we refer to ourselves as the "New Theatre" to "Nottingham New Theatre" to ensure we are inline with the current name for the theatre.

**Comment by phgeller** [comment]
This includes the main header at the top of every page!

**Comment by wjdp** [comment]
> This includes the main header at the top of every page!

Gah, but the logo looks pretty!
