### ISSUE TITLE
Link list item spacing feels off

### ISSUE THREAD

**Issue by samozzy** [newtheatre/history-project#1619]
<img width="389" alt="Screenshot 2020-07-16 at 1 54 22 PM" src="https://user-images.githubusercontent.com/15388319/87673098-dc51d500-c76b-11ea-8e01-f9fd74c06cc4.png">

I'm not a fan of the bunching up in pairs that appears to have happened here.

[Source](https://history.newtheatre.org.uk/years/18_19/a_girl_is_a_half_formed_thing/)

**Comment by wjdp** [comment]
Ew, does indeed look off
