### ISSUE TITLE
2020-Present Shows

### ISSUE THREAD

**Issue by samozzy** [newtheatre/history-project#1700]
List of shows that happened from 2020 to be added as we get back up to date...

**Comment by helenahunt** [comment]
https://uniofnottm-my.sharepoint.com/:x:/g/personal/ldyhh5_nottingham_ac_uk/ER4UpbQ96bRCsi-UToVQEAUByv3TqfkUJ5aenVf7tquU9Q?e=w5Bs2f

**Comment by helenahunt** [comment]
Here is a link to the spreadsheet with all the past shows information from 2020 onwards!

**Comment by BenWoodford76** [comment]
@helenahunt can I delete the pages on the spreadsheet that are now on the history site?

**Comment by samozzy** [comment]
Is this now closed with #1724?

**Comment by BenWoodford76** [comment]
@samozzy Potentially apart from this current year?

**Comment by samozzy** [comment]
In which case I'll consider this us up to date with the current season 🥳 
Closed with #1724
