### ISSUE TITLE
Caroline Blinkhorn, Caroline Blinkham same person?

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#176]
http://history.newtheatre.org.uk/people/caroline_blinkhorn/

http://history.newtheatre.org.uk/people/caroline_blinkham/

Both around 01-03

**Comment by phgeller** [comment]
Caroline Blinkhorn is correct!

*------------------*
*Philip Geller*

*M: 07754 056896*
*E:  Philip.Geller@gmail.com <Philip.Geller@gmail.com>*
*W: www.philgeller.co.uk <http://www.philgeller.co.uk>*
