### ISSUE TITLE
Hannah Steven, Hannah Stevens same person?

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#178]
http://history.newtheatre.org.uk/people/hannah_steven/
http://history.newtheatre.org.uk/people/hannah_stevens/

Both 01-02

**Comment by phgeller** [comment]
Hannah Stevens is correct



*------------------*
*Philip Geller*

*M: 07754 056896*
*E:  Philip.Geller@gmail.com <Philip.Geller@gmail.com>*
*W: www.philgeller.co.uk <http://www.philgeller.co.uk>*

**Comment by wjdp** [comment]
Should be corrected, however http://history.newtheatre.org.uk/people/hannah_steven/ still exists?

**Comment by wjdp** [comment]
Part of a larger problem, this now fixed
