### ISSUE TITLE
Which one of these is right: Cowlinshaw / Cowlishaw

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#179]
http://history.newtheatre.org.uk/people/matthew_cowlishaw/
http://history.newtheatre.org.uk/people/matthew_cowlinshaw/

**Comment by phgeller** [comment]
cowlishaw is correct.

the one *with the N* is WRONG!



*------------------*
*Philip Geller*

*M: 07754 056896*
*E:  Philip.Geller@gmail.com <Philip.Geller@gmail.com>*
*W: www.philgeller.co.uk <http://www.philgeller.co.uk>*
