### ISSUE TITLE
Do some placeholder text for the /collect/person/ form

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#201]
The textareas have no placeholders

**Comment by nhyty** [comment]
@BenWoodford76  https://history.newtheatre.org.uk/collect/person/?name=ben_woodford this page for you

**Comment by BenWoodford76** [comment]
There's already placeholders in most of the text boxes.....

**Comment by BenWoodford76** [comment]
Where in the repo is the file for this page?

**Comment by nhyty** [comment]
https://github.com/newtheatre/history-project/blob/master/_content/collect/person/index.html
