### ISSUE TITLE
Peter Carey / Cary

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#203]
See http://history.newtheatre.org.uk/people/peter_carey/ and http://history.newtheatre.org.uk/people/peter_cary/

**Comment by phgeller** [comment]
Peter Cary is correct

*------------------*
*Philip Geller*

*M: 07754 056896*
*E:  Philip.Geller@gmail.com <Philip.Geller@gmail.com>*
*W: www.philgeller.co.uk <http://www.philgeller.co.uk>*
