### ISSUE TITLE
Home page layout / design

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#21]
Long running issue for design of home page

**Comment by wjdp** [comment]
The content we have is alright, the 'wall of text' layout is not. I would look to add a recently updated list of shows (may not be technically possible, a random list would be more so) and a number of production shots.

A number (~4/5) production shots could be shown left-to-right. The photos are randomly selected from a decade and sorted old->new.

**Comment by phgeller** [comment]
Ive had some ideas for this - including a twitter feed

*------------------*
*Philip Geller*

*M: 07754 056896*
*E:  Philip.Geller@gmail.com <Philip.Geller@gmail.com>*
*W: www.philgeller.co.uk <http://www.philgeller.co.uk>*

**Comment by wjdp** [comment]
Attacking this today/tomorrow

**Comment by wjdp** [comment]
Major design changes made ( #205 ), still to do:

- [ ] New/launched banner

Anything else @phgeller ?

**Comment by wjdp** [comment]
Done
