### ISSUE TITLE
Removed pages still exist in gh-pages (and thfr the live site)

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#221]
Example #178: http://history.newtheatre.org.uk/people/hannah_steven/ should not exist but persists in gh-pages.

Sort an automated removal of pages, possibly by refactoring the build and deploy scripts.

**Comment by wjdp** [comment]
A build with `RESET` set to `true` fixes this, perhaps a purge every now and again?

**Comment by nhyty** [comment]
I have tried this for Adam H Wells and Adam H. Wells and it still persists

**Comment by wjdp** [comment]
Adam wells is a separate issue (see acc9531ff94109d6f9b664e1229662bf0d8c48e6 for fix), this issue now fixed by force pushing the gh-pages branch into a separate repo, gibbledy gob
