### ISSUE TITLE
Rather large build backlogs happen

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#224]
![image](https://cloud.githubusercontent.com/assets/1690934/10250246/8f930822-6921-11e5-85c1-d3d69da6e243.png)

When using the web interface to edit, many commits are made that in turn make many travis builds

6 mins \* 100 commits = 10 hours of backlog

Possible solutions
- Have the build script check if there are builds ahead of it, if so cancel
- Make concurrent builds happen
- Speed up the build (~1.5 mins realistic with Jekyll3 #118 )

**Comment by wjdp** [comment]
I've turned on concurrent builds, seems 5 are running in parallel now, not sure if this will have adverse affects

**Comment by nhyty** [comment]
Is this still an issue?

**Comment by wjdp** [comment]
Sort of, will keep open, but no clear solution at the moment

**Comment by wjdp** [comment]
It's almost a year later, this hasn't been a real issue. If we wanted to we could clog the system but no-one's done that.
