### ISSUE TITLE
Investigate and test Git Large File Storage for storing assets, photos etc

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#228]
https://git-lfs.github.com, #197 

https://github.com/newtheatre/history-project-lfs-test

We can store lots of images/videos of this but is a very new technology. Could be buggy or slow. Investigate and test a version of the repo migrated to LFS.

**Comment by wjdp** [comment]
It works, and is a good solution **buuut** near impossible for non-technical users. We're doing SmugMug #229 #232

**Comment by nhyty** [comment]
YAY
