### ISSUE TITLE
Role icon for photography in people lists

### ISSUE THREAD

**Issue by nhyty** [newtheatre/history-project#243]
There should be an image to go by the photographer for a show like all the other crew members have, i suggest a camera.

**Comment by wjdp** [comment]
There is for the role of 'Photographer', see the `_data/role-icons.yaml` file. However it may not cover cases 'Photopgraphy' etc. If you fancy having a look at what all the permutations of the role are and updating the role icon definitions, go for it.

(FYI, icons come from http://ionicons.com/ or https://fortawesome.github.io/Font-Awesome/icons/)

**Comment by nhyty** [comment]
have fixed in f15ff96
