### ISSUE TITLE
Cast/Crew list data from 2014/15 from Darcy Graham

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#249]
## The Infant

![12086867_1057307407635123_1360927035_n](https://cloud.githubusercontent.com/assets/1690934/10435832/6427b6d2-711a-11e5-8347-57dba2692636.jpg)

Harry Bridge was an operator for that too, Dave Hanks didn't stage manage, and some girl called Lucia Choi did stage manage
Oh and Joanna Manning stage managed that instead of Lydia Phillips

## Doubt

Harry's name is spelled wrong

![12071447_1057308160968381_1688881174_n](https://cloud.githubusercontent.com/assets/1690934/10435969/57b20d34-711b-11e5-9baa-e6fe8be29887.jpg)

## Bent

![12092233_1057309720968225_867114555_n](https://cloud.githubusercontent.com/assets/1690934/10435972/5fea0902-711b-11e5-8e6c-738a59ddda7a.jpg)

Harry's name is spelled wrong

## Mastromas

![12092218_1057310900968107_1477908294_n](https://cloud.githubusercontent.com/assets/1690934/10435976/65c8a0d6-711b-11e5-8b58-131465c2bca1.jpg)

Ben Williamson may or may not be real

**Comment by nhyty** [comment]
I will deal with this

**Comment by nhyty** [comment]
In spreadsheet, can now be closed

**Comment by wjdp** [comment]
Cheers #149
