### ISSUE TITLE
Add smugmug pointers to shows

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#271]
Did a few here f1155afd9a42c423f8a5d8464e0b94a4e0c80481 but have since added the rest of the Flickr export

**Comment by nhyty** [comment]
Have added all from 2014-15, am working on 203-14 next

**Comment by nhyty** [comment]
2013-14 done, now for 2012-13

**Comment by nhyty** [comment]
Most of these are now done, for those that are on smugmug currently

**Comment by wjdp** [comment]
As of now, there are 159 albums on SM, and 87 shows in the repo with a smugmut attr. We're still missing a few :rabbit:

**Comment by nhyty** [comment]
How do you see more than just the first page of api keys?

**Comment by wjdp** [comment]
Follow link on this page http://history.newtheatre.org.uk/docs/shows/

**Comment by nhyty** [comment]
I *think* this is now done

**Comment by wjdp** [comment]
138 / 166

**Comment by nhyty** [comment]
So, 4 shows need pages and there are 17 galleries that don't match with a show for one reason or another. Therefore, i only need 145 and have just added in the last 7, so i think this can be closed

**Comment by wjdp** [comment]
Sweeeet, thanks v much

**Comment by wjdp** [comment]
Annoying, Lear and Cheque are affected by the #246 Ghetto SmugMug Bug. Have removed for the time being (to allow Travis to pass) but will fix in #314 .
