### ISSUE TITLE
Facebook production shots onto SmugMug

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#274]
With Flickr done, time to scrape Facebook.

As before should get the highest quality possible.

**Comment by nhyty** [comment]
Working on it

**Comment by nhyty** [comment]
2014-15 done, working way through 2013-14 slowly :smile:

**Comment by wjdp** [comment]
Bored Nathan is best Nathan

**Comment by nhyty** [comment]
2013-14 done, now for 2012-13

**Comment by nhyty** [comment]
I think that all the ones from the facebook page are done, please check though.

**Comment by wjdp** [comment]
Sweet, could you grab these two as well:

- Bed at lakeside, https://www.facebook.com/media/set/?set=a.10151189812651460.476032.103029916459&type=3
- Bannlad vists https://www.facebook.com/media/set/?set=a.10150669392836460.416379.103029916459&type=3

**Comment by nhyty** [comment]
Done and done
