### ISSUE TITLE
Limit the number of production shots displayed initially on show pages

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#278]
We only should see 1/2 rows of images. Hide the rest on page load and display when a button is pressed...

- [x] Limit photos
- [x] Link to SM album

**Comment by nhyty** [comment]
you beat me to it :)

**Comment by wjdp** [comment]
:smirk: I'd like to be able to access them through this site as swapping between sites when browsing a lot of shows could get quite tiresome

**Comment by nhyty** [comment]
fair enough, just an idea. I feel we should have a link to the smugmug site somewhere on the site

**Comment by wjdp** [comment]
Oh yeah, there will be this too

**Comment by nhyty** [comment]
Can this be done soon, some of the albums have well over 100 shots.

**Comment by wjdp** [comment]
Yep, hoping to do this weekend

**Comment by wjdp** [comment]
Strike that, smashing it now
