### ISSUE TITLE
Investigate use of Git LFS for asset storage

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#280]
PDFs for publicity materials is nice but filesizes are big. Have a look at using the LFS space we have for this.

**Comment by nhyty** [comment]
I think we should be looking to put programmes on here if we can.

**Comment by wjdp** [comment]
Definitely, we can and do, they're just harder to find than posters.

**Comment by nhyty** [comment]
I should be able to add last years as I have the raw electronic versions of them all, will also collate this years as we go.

**Comment by wjdp** [comment]
Great! Please do
