### ISSUE TITLE
Mobile styling

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#31]
A little has been done for proper mobile styling. A review should be done once the site layout has settled to make the mobile layout attractive and usable.
- [x] Navbar
- [ ] Layout reorganising for single column
- [ ] Image gallery, awful! (make flexbox)
- [x] Combining resources (one css/one js)
- [x] Image optimise
- [x] Touch target sizing
- [x] Person record
- [x] Search bar
- [x] Decade list touch target sizing
- [x] Prevent large image downloads ( #188 )

**Comment by wjdp** [comment]
- Breadcrumbs are badly broken on mobile
- About / Docs subnav alignment

**Comment by wjdp** [comment]
Good enough for launch

**Comment by wjdp** [comment]
Flexbox meta row needs collapsing on mobile, maybe 2x2

**Comment by nhyty** [comment]
Hasn't some of this been done i.e. the flexbox

**Comment by wjdp** [comment]
Some of it has, needs a sit down audit though

**Comment by wjdp** [comment]
This will take a while to do properly, will chip away at over time

**Comment by nhyty** [comment]
Can you at least do the search bar next please

**Comment by wjdp** [comment]
I don't think anything is broken on mobile anymore. Everything is now built with mobile in mind. Closing now.
