### ISSUE TITLE
Lakeside Lysistrata

### ISSUE THREAD

**Issue by nhyty** [newtheatre/history-project#316]
Needs adding, event is here https://www.facebook.com/events/513929165335656/

**Comment by nhyty** [comment]
done it

**Comment by samozzy** [comment]
Is this the first Lakeside/NNT show? The Facebook event says yes, but there have been [previous shows](https://history.newtheatre.org.uk/seasons/lakeside/) performed in the space.

**Comment by nhyty** [comment]
It is the first collaboration show

**Comment by samozzy** [comment]
Cool, will update history appropriately. Ta.
