### ISSUE TITLE
Do better with the Next / Previous year buttons on /year pages

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#33]
Make them pretty, also add keyboard shortcuts to left and right arrow keys.

**Comment by phgeller** [comment]
Yeh...is there no way we can get these back to the top of the page? I liked
them on the right hand side, maybe just above where the committee listings
start?1


*------------------*
*Philip Geller*

*M: 07754 056896*
*E:  Philip.Geller@gmail.com <Philip.Geller@gmail.com>*
*W: www.philgeller.co.uk <http://www.philgeller.co.uk>*

**Comment by wjdp** [comment]
I've got an idea of what in want to do with it. a sort of design combo with the breadcrumbs. will be sorted later

**Comment by wjdp** [comment]
Breadcrumbs design is updated, will have a look at this soon
