### ISSUE TITLE
Year graph a little flat on show pages 

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#333]
![image](https://cloud.githubusercontent.com/assets/1690934/10871210/6e905070-80d8-11e5-953d-090795ab490a.png)

Only happens on show pages, weird

**Comment by wjdp** [comment]
Has been disabled on show pages for time being, on backlog now

**Comment by nhyty** [comment]
Needs enabling again

**Comment by wjdp** [comment]
Ah yes, will do

**Comment by wjdp** [comment]
Hmm broken on production yet works on local dev:

![image](https://cloud.githubusercontent.com/assets/1690934/11494831/152c537a-97fe-11e5-8771-72aef3cdf396.png)

**Comment by wjdp** [comment]
Aaand on another build:

![image](https://cloud.githubusercontent.com/assets/1690934/11494892/804a4964-97fe-11e5-8e11-5bf41f5a9aa6.png)

Going to guess something is going on with the order of plugin execution. Non-deterministic order could cause this behaviour, A that depends on B can happen before or after B depending on how the build feels, not good.

**Comment by wjdp** [comment]
Because of #402 this *should* no longer be a thing
