### ISSUE TITLE
New views (Edinburgh, NSDF, Presidents, Fellows, Venues)

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#337]
Show all Edinburgh shows on a single page for browsing. Think about other 'views' we may like.
- [x] Edinburgh shows, shows by season
- [ ] NSDF shows (deps #12)
- [x] Presidents (from committee listings)
- [x] Fellows (from people records)
- [x] Venues (from show records)
- [x] Year of 19xx/20xx graduation groups
- [x] Playwright

**Comment by nhyty** [comment]
Yes to this, also shows taken to NSDF?

**Comment by wjdp** [comment]
:+1:

**Comment by wjdp** [comment]
Some done, bumped to next milestone

**Comment by nhyty** [comment]
Has been playwright been done?

**Comment by wjdp** [comment]
erm, yeah

**Comment by nhyty** [comment]
Has the graduation group part of this not been implemented???

**Comment by wjdp** [comment]
Sort of, see: https://history.newtheatre.org.uk/people/grad/

It doesn't really work on a single page as there's too many elements. Tried to replace this with the people search.

**Comment by nhyty** [comment]
Can this be closed with the last bit being merged into #12

**Comment by wjdp** [comment]
Yep
