### ISSUE TITLE
Collect posters from the physical archive

### ISSUE THREAD

**Issue by nhyty** [newtheatre/history-project#341]
We have physical copies of these posters, we should digitize them

- [ ] imaginary invalid
- [ ] black comedy
- [ ] picture of dorian gray
- [ ] murder in the red barn
- [ ] Me old cigar
- [ ] The Possessed
- [ ] Heloise
- [ ] Loot
- [ ] Long Day's Journey Into Night
- [ ] In the Clapshack
- [ ] Lysistrata (Lakeside)
- [ ] The Vagina Monologues 2014
- [ ] Fresher the Musical
- [ ] URN Bombay Bicycle Club gig
- [ ] NNT AGM
- [ ] Absurd Person Singular
- [ ] Cast Aside
- [ ] The Flu Season
- [ ] Cradle Me
- [ ] Anything to Declare
- [ ] House of Bernada Alba
- [ ] Twin SS
- [ ] The Importance of Being Earnest
- [ ] After The End
- [ ] Through the Looking Glass
- [ ] Tests/Afternoon Tease/Froots
- [ ] Froots
- [ ] Mrs Warren's Profession
- [ ] Crave/No Exit
- [ ] Cabaret
- [ ] Half a Heartbeat
- [ ] Inherit the Wind
- [ ] Nightcap
- [ ] Private Lives
- [ ] Journeys End
- [ ] Christie in Love/Around the Bend
- [ ] The Lonesome West 2011 (higher res needed)
- [ ] Wild West End (higher res needed)
- [ ] Cheque Please (higher res needed)

**Comment by wjdp** [comment]
These ones we have in the office?

**Comment by nhyty** [comment]
on the wall

**Comment by nhyty** [comment]
looking through the ones in the office soon

**Comment by wjdp** [comment]
Thought of a better capture method for things on the wall?

**Comment by nhyty** [comment]
Nothing is actually on the wall that isn't in a frame

**Comment by wjdp** [comment]
Ah, scanny scanny then

**Comment by nhyty** [comment]
yeah, just actually need to do it at somepoint

**Comment by phgeller** [comment]
Im fairly sure the stuff on the wall in the foyer is actually not original?

I think the originals are with the uni archives..

I am currently waiting for a quote from them to professionally digitize
everything they have for us :)



*------------------*
*Philip Geller*

*M: 07754 056896*
*E:  Philip.Geller@gmail.com <Philip.Geller@gmail.com>*
*W: www.philgeller.co.uk <http://www.philgeller.co.uk>*

**Comment by nhyty** [comment]
Many more have been found in the office, would be brilliant to have done for the dinner. Any news on the quote @phgeller ? @wjdp, can you help sort them out at some point.

**Comment by wjdp** [comment]
How many we talking? With new MFDs on campus I've checked the [costs](https://www.nottingham.ac.uk/it-services/services/print-copy-scan.aspx) and it looks like scanning is free now. We could just do a big ol' trip to the library.

**Comment by nhyty** [comment]
There are 50 odd, if not more

**Comment by wjdp** [comment]
![d](http://i.imgur.com/DTKoO.jpg)

There are no fun pictures about scanning :cry:

**Comment by phgeller** [comment]
I am waiting to hear back about a quote to get the stuff that is already in the archives scanned. They are being a bit useless. I actually emailed them over the weekend, and then nick tried to call them today.

**Comment by nhyty** [comment]
Closing as a duplicate of #514
