### ISSUE TITLE
People links to news stories

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#357]
e.g. http://www.ayoungertheatre.com/feature-director-liz-stevenson-jmk-trusts-young-director-of-2015/ and the award she got a couple of months back

Would be nice to collect things like this under the alumni bios

**Comment by nhyty** [comment]
Agree, but same issues as review, ie how do we ensure the link doesn't become a dead link

**Comment by wjdp** [comment]
Trust that external sites are responsible? \s

Nah I'll look into solutions, Wayback machine or similar

**Comment by wjdp** [comment]
Has been agreed on, fields specced just need to implement.
