### ISSUE TITLE
Add first ~10 bios

### ISSUE THREAD

**Issue by nhyty** [newtheatre/history-project#358]
Is it worth adding alumni bios now? There are currently 8, and if so, is there any particular template, or just what you have done for your 3?

**Comment by wjdp** [comment]
Not really sure about format or when we should start. @phgeller any thoughts?

**Comment by phgeller** [comment]
Can we chat about this at the weekend? I will be with Nick on Sat PM if
you're around?

100% want to get this going now :)


*------------------*
*Philip Geller*

*M: 07754 056896*
*E:  Philip.Geller@gmail.com <Philip.Geller@gmail.com>*
*W: www.philgeller.co.uk <http://www.philgeller.co.uk>*

**Comment by wjdp** [comment]
Y

**Comment by nhyty** [comment]
I am around too

**Comment by wjdp** [comment]
We should start adding them. I'm going to spec the format for links and other fields we want in the next few days.

**Comment by wjdp** [comment]
I've update the people docs to nail down attribute names: http://history.newtheatre.org.uk/docs/people/

We should start adding, then when I get a chance to add in and style the new fields we'll see what it all looks like.

**Comment by nhyty** [comment]
Should I start adding these then?

**Comment by wjdp** [comment]
YES :P

Will Pimblett

**Comment by wjdp** [comment]
Done, thanks @nhyty
