### ISSUE TITLE
Portrait and landscape photos together look bad

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#38]
Do something to make them not

![image](https://cloud.githubusercontent.com/assets/1690934/7335218/c127178a-eba8-11e4-9c16-1580a243e30a.png)

**Comment by wjdp** [comment]
It gets worse!

![image](https://cloud.githubusercontent.com/assets/1690934/9722030/7ea31670-559d-11e5-827d-84b532b521a8.png)

**Comment by wjdp** [comment]
Now cropped, should look into making thumbs centred in container as ugly

![image](https://cloud.githubusercontent.com/assets/1690934/9724036/86e41c64-55c8-11e5-8ace-727904b3e812.png)

**Comment by wjdp** [comment]
Should be resolved by SmugMug migration and #211 (flexbox)

**Comment by nhyty** [comment]
This appears to have been fixed
