### ISSUE TITLE
Support Open Graph

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#382]
Is meta-data to make links to the site look pretty on facebook.

Open Graph - http://ogp.me/
Current state of the site in OG - https://developers.facebook.com/tools/debug/og/object?q=history.newtheatre.org.uk
- [ ] Generic content pages should have a generic image, title and excerpt
- [ ] People should have title, headshot and excerpt. Need a placeholder headshot.
- [ ] Shows should use their poster or equivalent.

Might be an idea to implement an attribute for all pages, `display_image`, or similar which is an image to represent the page (poster, headshot, generic etc)

**Comment by davidtaylorhq** [comment]
Haha, I didn't even know this issue existed
