### ISSUE TITLE
Add shows from V Greatorex bio

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#386]
Couple of shows mentioned, http://history.newtheatre.org.uk/people/vanessa_greatorix/.

To be added in a single commit with message mentioning source, see 76b280ef7179de6bcd92a1f9ad2c92d25d026d76

**Comment by nhyty** [comment]
Closed in 7dcd16a

**Comment by wjdp** [comment]
She's Vanessa Greatorex, you've put the names in as Victoria Greatorix

:unamused:

**Comment by nhyty** [comment]
I'm a moron.

**Comment by wjdp** [comment]
It is known

**Comment by nhyty** [comment]
Sorry, will fix in the morning (properly)
