### ISSUE TITLE
'Report a problem with this page' quick message 

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#39]
Have a popup a bit like this one from helpful.io (labeled 'Report problem with page' or something like that):

![image](https://cloud.githubusercontent.com/assets/1690934/7337486/5829e782-ec23-11e4-84a0-ebb890ef9212.png)

Which creates an issue on the tracker with a link to the page it was made in, and without the need for a github account or leaving the history site.

Issues would probably be posted by @ntbot

**Comment by phgeller** [comment]
Looks good mate


*------------------*
*Philip Geller*

*M: 07754 056896*
*E:  Philip.Geller@gmail.com <Philip.Geller@gmail.com>*
*W: www.philgeller.co.uk <http://www.philgeller.co.uk>*

**Comment by wjdp** [comment]
:+1:
