### ISSUE TITLE
Estimate people fields

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#416]
- [x] Estimate field / fields a member was involved in (acting, directing, lx, set etc)

Will require storing this in a useful format, investigate

- [x] Estimate graduation year

Last show / committee member was on, needs a differentiation from a true graduation year

**Comment by nhyty** [comment]
As a part of this have a total number of shows shown somewhere perhaps?

**Comment by wjdp** [comment]
We gen an srole list for people-index in #560. This I think fulfils this.
