### ISSUE TITLE
Venue collection

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#420]
Small collection user `_venues/` for venue data. to be shown on venue show listing pages 

For https://history.newtheatre.org.uk/venues/new-theatre-studio-a/

```
---
title: New Theatre Studio A
title_short: Studio A
built: 2012
images:
  - ABC123
  - ABC124
location:
  lat: 52.938035
  long: -1.196260
---

Part of the Archaeology and Classics building left up when building was demolished.
Properly converted into a studio space in 2013, white to black walls, blue carpet to
vinyl floor, rig and drapes installed.

```

- [x] Implement collection
- [ ] Style on /venues/... pages
- [ ] Document collection

Ideas for additional fields please!

**Comment by nhyty** [comment]
If you could create the directory i will write some up over the next few days, will also do for #421

**Comment by wjdp** [comment]
I'm sure you can make a folder :P _venues and _seasons, files ext will be .md

Will Pimblett

**Comment by nhyty** [comment]
Where should i upload images for locations?

**Comment by wjdp** [comment]
Lets say `images/venues/...`

**Comment by wjdp** [comment]
Note for future me, revert 043efdef614911ca7846ed51b8a41d55914e0bca to get Nathan's venue work back

**Comment by nhyty** [comment]
Needs to have images like #515.

**Comment by wjdp** [comment]
Not a thing yet so have just updated the issue description
