### ISSUE TITLE
Separate venues by city

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#422]
![image](https://cloud.githubusercontent.com/assets/1690934/12002963/74c488dc-ab06-11e5-8d2c-982af70d97a2.png)

On the [/years/](https://history.newtheatre.org.uk/years/) 'archive' page separate between two (Nottingham and Edinburgh/External), will depend on data from venues collection ( #420 )

**Comment by nhyty** [comment]
would suggest having a city field, for either nottingham, edinburgh or anywhere else we might hve take a show, eg NSDF etc

**Comment by wjdp** [comment]
Oooh that's nice :+1:

**Comment by nhyty** [comment]
bump

**Comment by wjdp** [comment]
I am aware
