### ISSUE TITLE
Info from impact articles

### ISSUE THREAD

**Issue by nhyty** [newtheatre/history-project#424]
Info from impact on various shows in this year
http://www.impactnottingham.com/2006/11/fish-chips-and-mushy-peas/
http://www.impactnottingham.com/2006/12/448-psychosis-a-powerful-suicide-note/
http://www.impactnottingham.com/2010/10/the-retreat/
http://www.impactnottingham.com/2012/08/the-hand-me-down-people-edinburgh-fringe/
http://www.impactnottingham.com/2013/02/a-word-with-paradise/
http://www.impactnottingham.com/2013/02/a-word-with-musicalitys-wild-west-end-cast-crew/
http://www.impactnottingham.com/2012/09/the-fringe-diaries/
http://www.impactnottingham.com/2013/04/lysistrata-lakeside-arts-centre/
http://www.impactnottingham.com/2013/04/2magpies-present-serenade-antalya/
http://www.impactnottingham.com/2013/03/impact-is-serenaded-by-2magpies/
http://www.impactnottingham.com/2013/03/a-word-with-a-clockwork-orange/
http://www.impactnottingham.com/2013/03/nnt-uncut-osama-the-hero-by-dennis-kelly/
http://www.impactnottingham.com/2013/03/a-word-with-the-last-of-the-haussmans/

**Comment by nhyty** [comment]
There are many more, but i'm not bored enough atm.

**Comment by wjdp** [comment]
ha, fantastic

**Comment by nhyty** [comment]
Found all for now

**Comment by wjdp** [comment]
FYI Linking to reviews is going to be a thing at some point
