### ISSUE TITLE
Add Company field on show for externals

### ISSUE THREAD

**Issue by nhyty** [newtheatre/history-project#433]
Allows us to track which external companies have come to us and what shows they have done.

**Comment by wjdp** [comment]
:+1:

**Comment by wjdp** [comment]
it's `company: xyz`, go nuts

**Comment by nhyty** [comment]
Just needs putting on show pages now :)

**Comment by wjdp** [comment]
Yep that's the next step :P

**Comment by nhyty** [comment]
bump

**Comment by wjdp** [comment]
I am aware, see #561
