### ISSUE TITLE
Group similar venues

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#457]
have a `sort_venue` attribute to group venues in their views (if not present just use `venue`). Will sort grouping of similar venues such as Lenton, Zoo and NNT Studios

![image](https://cloud.githubusercontent.com/assets/1690934/12172435/cacf4a7c-b548-11e5-8a11-a8465962b3e2.png)

**Comment by nhyty** [comment]
#422

**Comment by wjdp** [comment]
I'd do this together with the city separation
