### ISSUE TITLE
Jazz up the history page

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#474]
[Wall of text](https://history.newtheatre.org.uk/history/) is lovely and all, but have a gander at improving.
- [ ] Review and edit content
- [x] Style content nicely, break up the text, maybe add a timeline or something fun like that
- [x] Pictures! #65

**Comment by nhyty** [comment]
Do we want have the alumni events bit at the bottom or as a separate page? I feel it is out of place on this page, but keeping a record would be nice, including some links to photos too for people to find.

**Comment by wjdp** [comment]
It feels out of place on this site, is more a thing for the main website. Buut it should be mentioned and it is on the homepage so cut it please.

**Comment by nhyty** [comment]
Might ask Emma to have a look over this page

**Comment by nhyty** [comment]
@samozzy if you get bored

**Comment by samozzy** [comment]
After 30 seconds of googling, something like this with less obnoxious animations? 
https://codyhouse.co/demo/vertical-timeline/index.html

**Comment by nhyty** [comment]
i also meant like the words bit

**Comment by samozzy** [comment]
We reference shows in this a lot. Should we create placeholders and link to them within this page where necessary?

**Comment by davidtaylorhq** [comment]
> We reference shows in this a lot

What shows does the page reference? I don't see any references to shows... (I might just be blind though)

**Comment by samozzy** [comment]
Now less wall-of-text. Also added STUFF, Lakeside, Uncut/Fringe, Alumni Dinner dates. [long png](https://cloud.githubusercontent.com/assets/15388319/23574627/4f04eb8c-0078-11e7-9523-236346505fd7.png)

Thoughts? More pictures, I think.

@davidtaylorhq Shows referenced before my additions: A.A. Milne’s ‘Mr Pim passes by’; Coriolanus; ‘Taming of the Shew’; 'St Joan'. All from the past (pre-1985 from the looks of things).

**Comment by wjdp** [comment]
Nice work @samozzy.

The 'vertical timeline' is something I've had in mind for a while but as with many things haven't quite gotten around to. Your edit's fit well with this. 

What I think we should/could do : create a YAML file `_data/timeline.yml` with a nice structured syntax with this content. Then replace history page with a generated timeline from this data. Should make editing / adding to it easier.

**Comment by nhyty** [comment]
This sounds like a really good idea :)

**Comment by samozzy** [comment]
Will translate into yaml at some point soon.
Would milestones be useful? 'First Fringe show', 'first graduate', 'first STUFF show' - attaching show by some id to the year section? Or would that be a separate thing for within the show itself?
In other words, would we prefer to highlight this on the history page, the show page, or both?

**Comment by davidtaylorhq** [comment]
I think those kind of things are risky - do we really know what the first fringe show was? The Nottingham Theatre Group was originally set up to put on an Edinburgh show... 

What is currently the "fringe" season used to be called "uncut", and that was a purely arbitrary name change, so giving the first show labelled "fringe" any kind of special mention seems a bit overkill

**Comment by samozzy** [comment]
I guess it's whatever we want to define it as. Could do both 'First Uncut' and 'First Fringe', but you get the idea. More looking for thoughts about the concept, if it's something we should do and where it should go - rather than precisely which things are covered.

**Comment by davidtaylorhq** [comment]
If we can do it, I think it would be great. My point is that I'm not sure it's feasible with the information we have available

**Comment by samozzy** [comment]
Could see it being useful within this list as-is for 'first's and 'earliest's. I'll have a think.

**Comment by samozzy** [comment]
Copied all data into yaml datafile :smile:

**Comment by samozzy** [comment]
Following discussion over at #742, we should look at adding some graphics to this, a combination of 3rd party and original work.

**Comment by nhyty** [comment]
For first shows such as unscripted and lakeside would suggest the poster of that

**Comment by nhyty** [comment]
If I were to get a selection of photos together for this could someone add them in and style it? @samozzy @wjdp ??

**Comment by samozzy** [comment]
I can certainly add them in. I'll put the older logos in when I next have time (very busy with coursework at the mo).

**Comment by wjdp** [comment]
I can help out at some point once there's a PR

**Comment by samozzy** [comment]
@nhyty Any joy on those photos?
What's left for the review/edit content checkbox?

**Comment by nhyty** [comment]
Will make a new folder in the HP section today and populate with the three we already use and then a selection of others to break up the text 😄

**Comment by nhyty** [comment]
mention some of #796 in here

**Comment by nhyty** [comment]
will actually get round to finding and putting together a useful album of images today to add some more to the page
