### ISSUE TITLE
Chasing dragons poster

### ISSUE THREAD

**Issue by nhyty** [newtheatre/history-project#477]
FINALLY!!!!!

![m205x285_ffffff](https://cloud.githubusercontent.com/assets/14825903/12361323/61c64f6c-bbb5-11e5-816a-a1e0b800e6cd.jpg)

**Comment by wjdp** [comment]
You been looking for a while?

**Comment by wjdp** [comment]
Adam's got a big one here:

![image](https://cloud.githubusercontent.com/assets/1690934/12361401/cfc09658-bbb5-11e5-8848-16f5f2797c22.png)

**Comment by nhyty** [comment]
Little while, its how many ways you have to search for it before you find it, next up is Cross Stitching
