### ISSUE TITLE
Policy on student adapted works

### ISSUE THREAD

**Issue by nhyty** [newtheatre/history-project#479]
Should this be marked as student written or not?

**Comment by wjdp** [comment]
???

**Comment by nhyty** [comment]
poorly worded by me, if we have a show that has been adapted by a student, Frankenstien by Jake Leonard or Gatsby by Laura, should we mark it as student written?

**Comment by wjdp** [comment]
hmm, thinking...

**Comment by wjdp** [comment]
Perhaps.

@njstevenson14 @phgeller care to weigh in? Should a show 'count' as student written, it will be grouped with other student written pieces on certain pages, an icon shows up next to it e.t.c. if it was just adapted by a student. See Nathan's comment above for examples.

**Comment by nhyty** [comment]
I feel like it should be

**Comment by nhyty** [comment]
I feel we should make the policy that if it was adapted from a book or film script by a student it is technically student writing, e.g. Great Gatsby by laura, but if it si adapting a Shakespeare it isn't, as it is just an editing job

**Comment by nhyty** [comment]
Also, devised/impoved pieces should be as well

**Comment by wjdp** [comment]
Yep, sounds good :+1:

**Comment by nhyty** [comment]
Where should we document this judgement?

**Comment by nhyty** [comment]
I feel we have reached a conclusion therefore closing issue

**Comment by wjdp** [comment]
> Where should we document this judgement?

In the commit message :)
