### ISSUE TITLE
De-shit the hero image

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#499]
![i](https://history.newtheatre.org.uk/images/posterwall-bodge.png)

was a bodge and never got made properly. @nhyty think you mentioned someone may be up for helping out with this?

Would be best with a decent mix of poster ages, keep the current large one or pick another old good looking one to be big.

**Comment by nhyty** [comment]
![12722170_10201592031677901_1215878427_o](https://cloud.githubusercontent.com/assets/14825903/13187621/2ab170ce-d744-11e5-999f-af9879ce790d.jpg)

**Comment by wjdp** [comment]
FYI GH has a new shiny upload/commit web UI
