### ISSUE TITLE
Twitter feeds on people records

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#501]
For someone's bio entry should we embed their twitter feed on the page?

**Comment by nhyty** [comment]
in my opinion, no

**Comment by samozzy** [comment]
I think this should be consented on a person by person basis. It should also have consistent branding with NNT, rather than Twitter.

**Comment by wjdp** [comment]
Unsure on the need for consent. If the data is on Twitter it's very public anyway and is already used on other sites. For us the tweets are behind a single link, why not merge them into a box where that link would be.

If you think I'm wrong please correct!

**Comment by BenWoodford76** [comment]
imho, we'd have to do it for every person, which is difficult for those with private accounts, also those older alumni who may not have a twitter account. Personally I think it'd look a bit naf having an embedded twitter feed for some people but not for others

**Comment by nhyty** [comment]
Also, twitter feeds are entirely out of our control so could potentially
have content that is not wanted on the site

**Comment by nhyty** [comment]
I am closing this for now as it doesn't seem like a useful thing atm
