### ISSUE TITLE
Decades page overflows on IE11

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#506]
![image](https://cloud.githubusercontent.com/assets/1690934/12842951/1b5d2c64-cbee-11e5-914c-f561fb0a6dd6.png)

![image](https://cloud.githubusercontent.com/assets/1690934/12843020/848434ee-cbee-11e5-9dd3-5c9c9fe2d88b.png)

**Comment by nhyty** [comment]
Given IE is no longer used, any objections to just closing this???

**Comment by BenWoodford76** [comment]
@nhyty Is the issue present when using Edge??

**Comment by nhyty** [comment]
@BenWoodford76 errrrr, i dont use edge

**Comment by wjdp** [comment]
Same as #660

**Comment by wjdp** [comment]
Closing re. #1252
