### ISSUE TITLE
Add a column to show if SM assets are included in the site somewhere on SM util pages

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#518]
Add a Y/N column here:

![image](https://cloud.githubusercontent.com/assets/1690934/13210154/29fad4ae-d924-11e5-9a90-a834e443d6ff.png)

to show if assets are used on the site. Will be useful to find assets that have been added to SM but missed from the site.
- [x] Show assets
- [x] Headshots
- [x] Venue photos

**Comment by nhyty** [comment]
Has this not been done??

**Comment by wjdp** [comment]
It has for shows, but not for headshots and venues.

**Comment by nhyty** [comment]
Fixed in a8b36cc
