### ISSUE TITLE
Person headshot mangled on mob-land

### ISSUE THREAD

**Issue by davidtaylorhq** [newtheatre/history-project#519]
Goes weird on mobile, will only has half a face.

![image](https://cloud.githubusercontent.com/assets/6270921/13218214/e01bdae0-d95f-11e5-9e89-23f689c90eb9.png)

**Comment by wjdp** [comment]
![image](https://cloud.githubusercontent.com/assets/1690934/13230329/d42ee64a-d99c-11e5-9d01-8e2c835b6a7e.png)

Cheers, looks like you're in landscape, photo shouldn't show at all in portrait. 

Possible culprit is the JS that auto centres image height for tall images. Will investigate.

**Comment by wjdp** [comment]
Reproduced on Android/Chrome

Only occurs when page is navigated to in portrait and phone is turned into landscape after. Expected behaviour when page is navigated to in landscape.

Due to this issue is low priority.
