### ISSUE TITLE
Notable events collection

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#53]
Another collection (akin to shows) for notable events. 

```

---
layout: event
title: Moved into refurbed building
date: 2012-11-09 (I think)
year: 12_13

---

![Photo of new building](photo.jpg)

Over the summer of 2012 the Archaeology and Classics building, which the theatre was a part of, was demolished leaving us a free-standing theatre at the heart of the University.
```

These events would show up somewhere on the years page.

**Comment by nhyty** [comment]
I think this should definately be a thing

**Comment by samozzy** [comment]
I think it should. It could go under the committee list.
We could use the history datafile to get the data for each year, too. 
![events](https://user-images.githubusercontent.com/15388319/42222737-e57f7e36-7ecd-11e8-9478-5ee469d2e0dc.png)

**Comment by wjdp** [comment]
Yes. I like Sam's implementation, the blocker to this previous is I wanted a fancy UI to show off the events, but we should start simple.
