### ISSUE TITLE
Project progress page

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#54]
A funky page with progress bars and shizzle. Hopefully useful metrics about how much information we've collected.

![img_20150427_134359](https://cloud.githubusercontent.com/assets/1690934/7347763/a0e29314-ece3-11e4-9f1a-4799219bfa35.jpg)

Perhaps look at a way to graph progress over time. Would probably require a script running periodically logging the metrics and a timestamp.

Metrics:
- Show pages
- Committees
- Shows with dates
- Shows with cast lists
- Shows with crew
- Shows with posters
- ~Heatmap of years and number of shows

**Comment by wjdp** [comment]
Similar thought, a table/spreadsheet page showing missing data. Useful for highlighting missing prod shots in series etc.

**Comment by wjdp** [comment]
@pickleshb Graphs!

**Comment by pickleshb** [comment]
WOOO

**Comment by wjdp** [comment]
Nothing has really come of this, closing for now
