### ISSUE TITLE
Build and maintain a 'UML' diagram for the site's data model

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#562]
It's getting a bit complicated, make a diagram.

**Comment by nhyty** [comment]
What is a UML?

**Comment by wjdp** [comment]
Google it

**Comment by pickleshb** [comment]
http://bfy.tw/55RC

**Comment by wjdp** [comment]
https://is.gd/JKXb7a

**Comment by wjdp** [comment]
Work in progress but something like this.

![image](https://cloud.githubusercontent.com/assets/1690934/15486139/6afa98f4-213b-11e6-8179-9ad27e39a839.png)

**Comment by wjdp** [comment]
As we have model definitions ( #621 ) with auto generating docs including runtime vars I don't think having a separate diagram is really needed. Is just another thing to go out of date.
