### ISSUE TITLE
Show/hide production shots at the top

### ISSUE THREAD

**Issue by samozzy** [newtheatre/history-project#567]
It's a bit of a pain to scroll through all the production shots to get to the content I want beyond them (use case: I wanted to view the shots, then look at cast and crew, had to scroll through all the shots first).
Propose duplicating the show/hide toggle to be at the top and bottom of the gallery.

**Comment by wjdp** [comment]
Yep, well aware of how annoying this is esp. on larger galleries. Issue is duplicate of #407.
