### ISSUE TITLE
Octicons broken

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#58]
Since refactor and minification of CSS octicons are broken.

**Comment by wjdp** [comment]
Due to bundling, URLs broken. Also affects fancybox

**Comment by wjdp** [comment]
Nope still broken (observed on Chrome mobile)

**Comment by wjdp** [comment]
@phgeller Can you check on your end if you can see the icons now?

**Comment by phgeller** [comment]
seem to be working

*------------------*
*Philip Geller*

*M: 07754 056896*
*E:  Philip.Geller@gmail.com <Philip.Geller@gmail.com>*
*W: www.philgeller.co.uk <http://www.philgeller.co.uk>*

**Comment by wjdp** [comment]
Shweett
