### ISSUE TITLE
Was 2008 DEARLY DEPORTED (Charlie Brafman) a NNT fringe show?

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#588]
```
2008, Stage, Angel, DEARLY DEPORTED, Underbelly, Charlie Brafman
```
from http://www.spotlight.com/2010-5646-3090

**Comment by nhyty** [comment]
From wiki

> Each year, the New Theatre takes one or more 'official' shows to the Edinburgh Festival Fringe and supports any number of shows being performed and produced at the fringe by its members. In 2007, these shows included an adaptation of 'Alice Through the Looking Glass'(New Theatre[5]), 'Dearly Deported' by Charles Brafman (Ankle Productions)[6] and 'Slippery Soapbox: Spotbanded Skat' (ShutYOface Productions).

**Comment by wjdp** [comment]
Ah, paging #561

**Comment by nhyty** [comment]
However, the lines of what an nnt show was at edinburgh were very blurred, see cast aside. Als oand ankle productions show but while they were all students with nnt.
