### ISSUE TITLE
Add StuFF period

### ISSUE THREAD

**Issue by nhyty** [newtheatre/history-project#590]
Similar to what is in place for Edinburgh, easy way to split StuFF off from the rest of the shows we do.

**Comment by wjdp** [comment]
The intention of periods was to separate shows much like the season attribute but it breaks temporal ordering hence why we got rid of several periods a while back (Lakeside &c).

Now periods separate shows into terms as acedemic years are rather disjointed with numeric ones. Where we are now is a nice compromise between chronological order and term splits. I'm very hesitant to split things up futher.

What may be an idea however is naming the *Edinburgh* period *Summer* instead, this would still have stuff in Spring but would clear up usage.

**Comment by wjdp** [comment]
In terms of making the list clearer #135 was doing something.

**Comment by nhyty** [comment]
While I kind of agree, StuFF is it's own entity, at the end of the year, which has many shows in a short period. It will always be the last thing in the year but i agree that too many is irritating. It is just a good way of separating this out as something which is 100% not a 'season'. I know that externals are included but this makes sense for chronology, same as lakeside.

**Comment by wjdp** [comment]
I think leave this for the time being and revist in a year or two once stuff has settled in.

**Comment by wjdp** [comment]
Going to close this for now
