### ISSUE TITLE
External link checking hangs on non-responsive web servers, travis times out, build fails

### ISSUE THREAD

**Issue by nhyty** [newtheatre/history-project#600]
Builds not finishing as HTML proofer times out, needs fixing.

**Comment by wjdp** [comment]
Am home now, will look at over next few days

**Comment by wjdp** [comment]
```
$ bundle exec rake test
++++++++++++++++++++++++++++++ HTML TEST ++++++++++++++++++++++++++++++
Running ["ScriptCheck", "LinkCheck", "ImageCheck"] on ["./_site"] on *.html... 
Found 27234 links in the cache...
Adding 1 link to the cache...
Removing 1 link from the cache...
Checking 27045 external links...
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

Will set to more verbose to combat this, not ideal though as more verbose not really wanted

**Comment by wjdp** [comment]
Mitigated this bug by disabling external link checking. Posted an issue in upstream for this https://github.com/gjtorikian/html-proofer/issues/340

**Comment by wjdp** [comment]
All fix, made timeout 15s to combat the odd slow connection.

https://travis-ci.org/newtheatre/history-project/builds/140895286
