### ISSUE TITLE
Link years on people pages to the year pages

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#617]
Click this, go to year

![image](https://cloud.githubusercontent.com/assets/1690934/16903771/3c0d4ebe-4c7f-11e6-989e-a56cb744c364.png)

**Comment by nhyty** [comment]
@samozzy, you happy to look at this when you're bored?

**Comment by samozzy** [comment]
Is there a neat way to do this? (ie, is there a handy function we could access?)
Current idea feels very bodge (manipulate the `WXYZ` number to result in `AB_YZ`)

**Comment by samozzy** [comment]
Functional version on the `people_year` branch. Needs styling work if we don't like yellow links.
Also slight amounts of bodge occurring :stuck_out_tongue_closed_eyes:
