### ISSUE TITLE
Create people stubs for famous alums

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#628]
Go through https://en.m.wikipedia.org/wiki/Nottingham_New_Theatre#Alumni, create people stubs for famous alumni filling out careers and other bits.

**Comment by wjdp** [comment]
Deploy nathanbot? @nhyty

**Comment by nhyty** [comment]
Will do soon

**Comment by nhyty** [comment]
see #665 too

**Comment by nhyty** [comment]
and see #522

**Comment by nhyty** [comment]
for @BenWoodford76

**Comment by BenWoodford76** [comment]
Will sort this as I've now got nothing better to do with my life :)

**Comment by nhyty** [comment]
Did you ever 😝

**Comment by BenWoodford76** [comment]
Have created the basic stubs and added all head-shots I could find for all on the Wikipedia list, will go through again tomorrow and fill out a basic bio for each
