### ISSUE TITLE
My head is really small, everyone else's is OK

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#634]
![image](https://cloud.githubusercontent.com/assets/1690934/18812249/1be24afe-82c6-11e6-8e91-c9396f006798.png)

Only on Android Chrome (not present in emulated Chrome desktop->Mobile), weird.

**Comment by nhyty** [comment]
No longer appears to be an issue

**Comment by wjdp** [comment]
Yep, not getting it here anymore. Re-open if it surfaces again.
