### ISSUE TITLE
Utility ordering broken

### ISSUE THREAD

**Issue by nhyty** [newtheatre/history-project#652]
The sort doesn't work anymore on here https://history.newtheatre.org.uk/util/smug-show-assets/

**Comment by wjdp** [comment]
When broken does the page have a purple or white background. (Screenshots in bug reports usually helpful)

**Comment by nhyty** [comment]
The issue here is the key column header has disappeared so the usage one is sorting that column, not the usage column

**Comment by wjdp** [comment]
Gotcha, took a bit but I got there.

**Comment by nhyty** [comment]
The sort is broken. Clicking on the arrow sorts the wrong column

**Comment by wjdp** [comment]
Can you be more descriptive? Which header sorts which column?

Following screencast shows sort working on filename, imagekey and usage on smug-show-assets:
http://fs.wjdp.uk/f/nthp-652.mp4
