### ISSUE TITLE
Search worker broken on IE11

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#660]
Search worker, currently in use on people-index, fails to initialise on IE11

![image](https://cloud.githubusercontent.com/assets/1690934/19873843/352a780a-9fb9-11e6-8af2-8da405c0f314.png)

**Comment by nhyty** [comment]
Given IE is no longer used, any objections to just closing this???

**Comment by nhyty** [comment]
appears to not be in edge either

**Comment by wjdp** [comment]
In the last six months IE was 3% of our users. I do not think we should bother working to make the site compatible with it but we should add a banner saying so.

**Comment by wjdp** [comment]
@nhyty Are you saying search works or not in Edge?

**Comment by nhyty** [comment]
@wjdp It works

**Comment by wjdp** [comment]
Closing re. #1252
