### ISSUE TITLE
Shows without a period don't appear on the year page

### ISSUE THREAD

**Issue by nhyty** [newtheatre/history-project#662]
Any shows that don't have a season allocated are not displayed, https://history.newtheatre.org.uk/years/84_85/ should have https://history.newtheatre.org.uk/years/84_85/mr_justice/ listed.

**Comment by wjdp** [comment]
- [ ] Shows missing the period attribute are not appearing.
- [ ] `period` is missing from the show definition so is not displayed on the debug table.
