### ISSUE TITLE
Search broken

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#663]
![image](https://cloud.githubusercontent.com/assets/1690934/19889833/2679bbec-a02f-11e6-9cb2-d4c9c1542961.png)

![image](https://cloud.githubusercontent.com/assets/1690934/19889840/2e71e568-a02f-11e6-80f3-e75f26ddfff3.png)

https://sentry.io/share/issue/38323935332e313735393433313437/

**Comment by davidtaylorhq** [comment]
Well that's gone badly

**Comment by wjdp** [comment]
Just a little

**Comment by wjdp** [comment]
![image](https://cloud.githubusercontent.com/assets/1690934/19900156/734e20c2-a05a-11e6-86ce-0f05ea9e684e.png), well yes



98ef370 fixed this
