### ISSUE TITLE
Images in incoming album

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#667]
Several groups of photos, some exist in shows, some do not (lacking show file).

- [x] CAB/The Plotters of Cabbage Patch Corner
- [x] WIT/The Wit to Woo
- [x] JE/Journey's End
- [ ] FV/Florence and Victoria
- [x] MAN/Man for all seasons
- [x] REVIEW/Edinburgh Review
- [ ] EDIN/NTG Edinburgh

Do we know who these photos came from?

**Comment by nhyty** [comment]
When should I tick these boxes?

**Comment by nhyty** [comment]
All of these have galleries of their own, and all apart from Flo and Vic and NTG ones are bound to a show

**Comment by wjdp** [comment]
If they're in place and have the same quality can you delete them from Incoming?

**Comment by nhyty** [comment]
These are all in the correct galleries, will clear incoming and close this issue now
