### ISSUE TITLE
Lightbox not maintaining aspect ratio

### ISSUE THREAD

**Issue by davidtaylorhq** [newtheatre/history-project#681]
If my browser window is narrow, the photo gets squished. This is bad

This:
![screen shot 2016-12-28 at 11 49 35](https://cloud.githubusercontent.com/assets/6270921/21521345/058e2c8c-ccf4-11e6-9725-07efb1233885.png)

Becomes this:
![screen shot 2016-12-28 at 11 49 28](https://cloud.githubusercontent.com/assets/6270921/21521346/0cc8a8b0-ccf4-11e6-8aeb-264aeafd4c1a.png)

**Comment by nhyty** [comment]
weird, doesn't do that for me
