### ISSUE TITLE
Replace Vagrant with Docker

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#695]
Now that [Docker supports Windows](https://docs.docker.com/docker-for-windows/) I suggest we replace the Vagrant setup with that of Docker. It's lighter weight and doesn't rely on a virtualbox install, rather using Hyper-V which isn't an Oracle product.

Possible issue:
> The current version of Docker for Windows runs on 64bit Windows 10 Pro, Enterprise and Education (1511 November update, Build 10586 or later). In the future we will support more versions of Windows 10.

@nhyty Does the current Vagrant conf work? What windows version are you on?

@tomtom5152 Thoughts?

**Comment by tomtom5152** [comment]
@wjdp My main issue with docker on Windows is that it only supports Windows 10. I suppose that issue is somewhat reduced by docker-machine still existing, but I believe that is officially discontinued now.

**Comment by nhyty** [comment]
I still can't  vagrant to work on my laptop, super irritating.

**Comment by davidtaylorhq** [comment]
See https://github.com/newtheatre/history-project/pull/731

**Comment by nhyty** [comment]
Closed in 24f1fa1
