### ISSUE TITLE
Revolt, She Said info

### ISSUE THREAD

**Issue by samozzy** [newtheatre/history-project#720]

**Comment by nhyty** [comment]
What???

**Comment by samozzy** [comment]
Closes with #721 
Mostly for the 'assignment' part for reasons. Does doing issues for shows make sense or just clutter the place? I feel like as we get more contributors it would make sense, to prevent double-work.

**Comment by BenWoodford76** [comment]
At the moment it just clutters things, but when we get more contributors maybe set an automatic reminder at the end of a show week saying "Have you created (In House + Fringe) files for this week?"

**Comment by davidtaylorhq** [comment]
By the time you've created an issue for a show you may as well just have committed it either to a branch or master

**Comment by samozzy** [comment]
> "Have you created (In House + Fringe) files for this week?"

I mean, it kinda makes sense for team publicity to do this given they make the programmes...
