### ISSUE TITLE
Collecting info and headshots (SJP, CCP)

### ISSUE THREAD

**Issue by nhyty** [newtheatre/history-project#727]
Collecting info and headshots on NNT people from [castingcallpro](http://www.castingcallpro.com/uk/search/actors?name=&keywords=nottingham+new+theatre&sex=&spotlight=&imdb=&aftra=&equity=&sag=&showreel=&voicereel=&headshot_360=&agent_represented=&heightfrom=1&heightto=300&height=&weightfrom=1&weightto=200&weight=&site_uid=1&end_lastlogin=2017-03-03+14%3A00%3A35&agefrom=16&ageto=99) and [stageprojobs](http://www.stagejobspro.com/uk/search/theatre-professionals?name=&keywords=nottingham+new+theatre&sex=&spotlight=&imdb=&aftra=&equity=&sag=&showreel=&voicereel=&headshot_360=&agent_represented=&heightfrom=1&heightto=300&height=&weightfrom=1&weightto=200&weight=&site_uid=23&end_lastlogin=2017-03-03+14%3A04%3A37&agefrom=18&ageto=99)

---

- [ ] http://www.castingcallpro.com/uk/actor/profile/tom-redican is https://history.newtheatre.org.uk/people/tom_walsh/

**Comment by wjdp** [comment]
Would have been nice for work on this to have been done in a branch. Could easily see whose had headshots added. (I know it's just one commit) :P

**Comment by wjdp** [comment]
We also want to add links from the person records to the SJP / CCP profiles.

**Comment by wjdp** [comment]
Note some people may have changed names as required in the industry:
- http://www.castingcallpro.com/uk/actor/profile/tom-redican is Tom Walsh

**Comment by nhyty** [comment]
How should we note this, just as a note field?

**Comment by wjdp** [comment]
Can do yeah, something to note for finding and linking to these.
