### ISSUE TITLE
Season Sorting

### ISSUE THREAD

**Issue by samozzy** [newtheatre/history-project#730]
Should it be chronological, or is this due to 'show sort' parameters?

Either way, the order seems confusing.

https://history.newtheatre.org.uk/seasons/fringe/

![fringe](https://cloud.githubusercontent.com/assets/15388319/23574232/52214ce2-0074-11e7-96f0-9f6d222fecc2.png)

**Comment by samozzy** [comment]
This does not explain why there is a 2011 show between two 2012 shows.

**Comment by nhyty** [comment]
Academic year Sam!!!!

**Comment by samozzy** [comment]
I mean, academic years still don't have time travel :stuck_out_tongue: Thanks.
