### ISSUE TITLE
Show Trailers

### ISSUE THREAD

**Issue by samozzy** [newtheatre/history-project#736]
Is anyone collecting show trailers and either putting the YouTube links in the show file as a link, or putting the video files on Smugmug?

**Comment by nhyty** [comment]
@samozzy would add to the end of the album on smugmug

**Comment by wjdp** [comment]
@samozzy Ideally they would be under 'Publicity Materials' but I've not added support for SM video yet

**Comment by samozzy** [comment]
Is the lack of video support due to the issues described in #672, or is it just a case of embedding the Smugmug player?
I agree that they should be under publicity materials rather than production shots.

**Comment by nhyty** [comment]
@wjdp but surely you also want them to be publicy accessible, which that folder is not

**Comment by wjdp** [comment]
@nhyty Same as all the show assets, folder is  unlisted not private

**Comment by nhyty** [comment]
Have created the gallery, will over time fill it with useful videos already on the smugmug

**Comment by wjdp** [comment]
This is now happening
