### ISSUE TITLE
Move hosting from GHP/CF > Netlify

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#737]
Came across https://www.netlify.com/ again a few days ago. Seems they have a free OSS plan and a half decent feature set (checking them off as I test them):

- [x] All the HTTPS
- [x] Configurable headers — https://www.netlify.com/docs/headers-and-basic-auth/
- [x] (thfr) Correct MIME types #672 #631
- [ ] Configurable redirects — https://www.netlify.com/docs/redirects/
- [x] Builds for PRs and non-master branches
- Other fun stuff — https://www.netlify.com/docs

It's also faster, first run was 2.115s vs 2.746s. See WPTs:

**GHP/CF**: https://www.webpagetest.org/result/170307_TD_ZEY/
**Netlify**: https://www.webpagetest.org/result/170307_ZJ_ZJZ/

Caching is currently disabled, with that on it should fly.

----

They build the site in a similar way to the way we do with Travis currently but with a worse UI. I would look to continue using Travis for this, it is better.

Master is hosted here: https://netlify.history.newtheatre.org.uk

**Comment by davidtaylorhq** [comment]
Looks awesome, would fix many annoyances with GH pages

**Comment by wjdp** [comment]
Potentially, currently deployment is falling all over the place

**Comment by wjdp** [comment]
Note on the current state of things:

- We are using Netlify to serve static binary assets (PDFs _&c_) on a separate deployment (https://assets.history.newtheatre.org.uk). This serves proper MIME types so allows browsers to use their inbuilt viewers for various file types.
- We get 'deployment previews' of PRs, very useful.
- The https://netlify.history.newtheatre.org.uk build of the site is operational with no major problems... well except it's slower. We'll keep both running and see if there's a solution for this.

**Comment by wjdp** [comment]
Netlify is still slower. Guessing they don't push pages to their edge cache until a request is made. We don't get _that_ much traffic so staying with GHP seems the better option for now.

Assets still with Netlify.

**Comment by tomtom5152** [comment]
Having just had another attempt at this I have some interesting results from it.

# New WPT results:
* Netlify: https://www.webpagetest.org/result/170903_MF_93e5a035805a839879d7c534173333fe/
* GH/CF: https://www.webpagetest.org/result/170903_GW_f64d59abaaccd546537ab130894a9609/

# Remarks
* Overall load times are still slower on Netlfiy by a few hundred ms, particularly for origin hits not cached at the edge. 
* Reloads are also slower on Netlify by a significant margin, however hits on the edge cache are comparable.
* Through the use of HTTP/2 push on CSS assets, I have managed to get the [Lighthouse](https://developers.google.com/web/tools/lighthouse/) Perceptual Speed Index down to 2433 from 3878. Arguably this is the metric that actually matters.
* Builds and deploys are quicker

# Next stages
* I'm now retrying without HTTP/2 on JS but using their bundling to go through CloudFront.
* I believe by introducing the netlify_deploy gulp task I may have broken deploy previews (assuming they come from the same Netlify app.
