### ISSUE TITLE
Docs: Style Guide

### ISSUE THREAD

**Issue by samozzy** [newtheatre/history-project#750]
A small style guide to promote consistent formatting in text, rather than code, should be added to the docs.
What should be in it?

- [ ] How to reference internal/external programmes (stage, television, film, etc.)
- [ ] ... More things!

Ideas welcome. I'll give the writing of it a go once we have enough things to include. When I've got some free time I'll have a proper think of more things myself.

Probably don't want it too strictly academic to maintain variety, but enough to not be horribly inconsistent.

**Comment by BenWoodford76** [comment]
is this good to close once the Contributors guide and editors guide have been updated? @samozzy ?

**Comment by samozzy** [comment]
@BenWoodford76 I think yes

**Comment by wjdp** [comment]
Good enough, contrib guide done in #1158
