### ISSUE TITLE
Docs: Contributing Guide

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#754]
Came across https://chris.beams.io/posts/git-commit/ today and combined with #750 we should draft a better contributing guide (currently [here](https://github.com/newtheatre/history-project/blob/master/CONTRIBUTING.md))

Unless anyone else wants a stab I'll give this a go soon.

Any ideas on this thread please.

## Resources

- https://chris.beams.io/posts/git-commit/ 
- http://ben.balter.com/2015/12/08/types-of-pull-requests/

**Comment by davidtaylorhq** [comment]
Nice article on commit messages, will definitely be striving for that. Would be great to have a small summary of that, as well as a link, on the contributing page.

**Comment by wjdp** [comment]
@davidtaylorhq Pretty much all I've got so far :D

**Comment by BenWoodford76** [comment]
What @davidtaylorhq said, has definitely made me think about how I do my commit messages

**Comment by wjdp** [comment]
Rediscovered http://ben.balter.com/2015/12/08/types-of-pull-requests/, good notes on types of PR

**Comment by wjdp** [comment]
Started on a draft of this

**Comment by samozzy** [comment]
Just come across this for pull request message content. Might be worth including some aspects of it. 
https://quickleft.com/blog/pull-request-templates-make-code-review-easier/

**Comment by wjdp** [comment]
@samozzy  I've considered these in the past though not come up with a compelling enough reason to. I don't think this project lends itself to a lot of the templates seen in the wild (for example see [Jekyll's issue template](https://github.com/jekyll/jekyll/blob/master/.github/ISSUE_TEMPLATE.md)).

Saying that, feel free to propose something!

**Comment by wjdp** [comment]
If you do, please put in own PR so we can discuss

**Comment by samozzy** [comment]
Putting this here for potential future reference (thanks, @wjdp) https://github.com/datatxt/awseome-yaml/blob/master/README.md

**Comment by wjdp** [comment]
Done in #1158
