### ISSUE TITLE
Capture the various incarnations of 'Backstage at...'

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#755]
As far as I know there are:
- The UoN produced videos: https://www.youtube.com/user/NottmUniversity/search?query=new+theatre
- The NUTS/NSTV produced videos: https://www.youtube.com/playlist?list=PLz-vEyD5_D2IpM7QXoIG7wN8GnCkmbb2Q
- And ones we've done ourselves

Capture these and put in an SM album. Please add titles to the SM objects (`Show Title (YYYY)`).

May motivate me to do #293

**Comment by nhyty** [comment]
Again, in the History Project folder for this gallery???

**Comment by wjdp** [comment]
Yeah, would think so

**Comment by nhyty** [comment]
@wjdp moved all videos already up into the correct foldres

**Comment by wjdp** [comment]
Fab

**Comment by nhyty** [comment]
what video format is wanted???

**Comment by davidtaylorhq** [comment]
@nhyty If you upload to smugmug, they re-encode anyway. So just get the best quality you can

**Comment by wjdp** [comment]
What @davidtaylorhq said. Try and download in the original formats if possible.

**Comment by wjdp** [comment]
Future note: for any youtube capture we need to do we should use https://rg3.github.io/youtube-dl/index.html.

It can do bulk downloads, handles resuming from streams breaking and should get the highest possible quality. Rather good.

**Comment by wjdp** [comment]
Wrong button

**Comment by nhyty** [comment]
these have all been downloaded from official youtube pages, will be added to show pages shortly

**Comment by nhyty** [comment]
these have now been added to the show pages so will close this as there is no more to be done in terms of the backlog
