### ISSUE TITLE
"Sound" role should have an icon

### ISSUE THREAD

**Issue by davidtaylorhq** [newtheatre/history-project#766]
People with the "Sound" role should get the same icon as "Sound Designer" (or another icon if there's a suitable one)

![screen shot 2017-03-19 at 17 02 45](https://cloud.githubusercontent.com/assets/6270921/24082954/060bcf86-0cc6-11e7-9665-f9fa6d188e6e.png)

**Comment by wjdp** [comment]
![image](https://cloud.githubusercontent.com/assets/1690934/24083041/abaad832-0cc7-11e7-9f92-51c7884347d8.png)

**Comment by davidtaylorhq** [comment]
Perfect
