### ISSUE TITLE
Review 'snippings' from old website

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#798]
From links on this page https://web.archive.org/web/20070301043107/http://www.newtheatre.org.uk:80/fringe.php

- [x] https://web.archive.org/web/20080905181103/http://www.newtheatre.org.uk/extra/persae.html
- [x] https://web.archive.org/web/20080723200301/http://www.newtheatre.org.uk/extra/castaside.html
- [x] https://web.archive.org/web/20081011163616/http://www.newtheatre.org.uk/extra/soapbox.html
- [x] https://web.archive.org/web/20080905183004/http://www.newtheatre.org.uk/extra/jeeves.html
- [x] https://web.archive.org/web/20071123060058/http://www.newtheatre.org.uk:80/magic/?p=38

**Comment by BenWoodford76** [comment]
Come On. Jeeves is not in the show archive, I assume this is because it didn't preview at NNT before it went up, and is only on the old site as NNT members took it up as part of a different production company?

**Comment by nhyty** [comment]
Honestly, who knows
