### ISSUE TITLE
Reviews: Comments / Notes

### ISSUE THREAD

**Issue by samozzy** [newtheatre/history-project#803]
[The Toyland Murders](https://history.newtheatre.org.uk/years/14_15/the_toyland_murders/) has a review from when Kite Tail Theatre Company performed it, attached to our version of the show, and a comment to say so.
Do we:
- Remove that review
- Not display the comment (no change)
- Display the comment in some form under the review (I suggest on a new paragraph, in italics)

Given `comment:` is reserved for debug mode, I suggest changing this to `notes:` for the instances it should be displayed.
My vote is for option 3.

**Comment by nhyty** [comment]
I also agree with option 3. @BenWoodford76  and @wjdp , any input??

**Comment by BenWoodford76** [comment]
@nhyty I also like option 3

**Comment by wjdp** [comment]
I'd suggest a field `note` (to align with person list). As we only have one list using this currently I wouldn't commit to the text under link, rather set the `title` attribute on the anchor.
