### ISSUE TITLE
Implement 'translator' attribute

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#83]
Line `playwright: Yasmina Reza (Translated by Christoper Hampton)` is bad, solution:

```
--
title: God of Carnage
playwright: Yasmina Reza
translator: Christoper Hampton
```

Implement this in layouts and docs

Also adaptions

```
---
title: "Mary Shelley's Frankenstein"
playwright: Mary Shelley
adaptor: Jake Leonard
```

**Comment by nhyty** [comment]
Can you implement this please will

**Comment by wjdp** [comment]
I can

**Comment by wjdp** [comment]
Completed by 0f4f5c4640e00d1d87c22a66fb939f878a035f73
