### ISSUE TITLE
Info from auditorium seats

### ISSUE THREAD

**Issue by samozzy** [newtheatre/history-project#839]
Following discussions, there is information on the auditorium seat plaques that is not currently here.
- [ ] Collect info that can add to existing archive (Dramsoc co-founder, etc.)
- [ ] Put additional information elsewhere? Do we want this? There are some poems and dedications there - are they in scope for this project?

**Comment by BenWoodford76** [comment]
@samozzy With regards to the second one, I think that having a record of it is useful, but personally I don't know how you'd fit that into the project

**Comment by samozzy** [comment]
That's my thought at present.

**Comment by wjdp** [comment]
Could stick it in the person's bio `/people/first-last/` They are 'attached' to people.

**Comment by samozzy** [comment]
Could we then add a filter in /people/ to view them all on one page?

**Comment by wjdp** [comment]
As it's bundled in the body of the people pages, no that would be infeasible. If we wanted them all on one page I'd do a data collection then put a for loop on a content page. Also double up in people's bios just to put something in there.

**Comment by samozzy** [comment]
Could we put the data in the people page to avoid duplication?

**Comment by wjdp** [comment]
The people pages may contain other content — say if the person submits a bio. I'm fine with the duplication here as there is a finite amount of it and the copy that'll go in the person record may mutate over time, and the copy in the seats data file will remain the same.

**Comment by samozzy** [comment]
Instead, given the seat data is attached to a person, can we add a loop in the person page: for seatdata, if name = name: display seat data?

**Comment by wjdp** [comment]
We could do, just not as a liquid for loop. Performance of that would be awful! (Liquid for loops are slow and this would add 70 odd iterations * 1800 people)

**Comment by wjdp** [comment]
Thinking about this further, this will be a really nice thing to have. These are people who have supported the theatre and it's important we recognise that. The `/seats/` or `/people/seats/` page should have a blurb about the campaign and a nice layout / design showing the names and dedications.

**Comment by samozzy** [comment]
> nice layout / design 
I immediately thought of the full seating plan of the auditorium with a star on each seat that has a dedication. Pretty and interactive, just a bit complex...

**Comment by BenWoodford76** [comment]
@samozzy I like this, also means you can add when other seats get a dedication/change their dedication. A log time down the road it would be nice to have a list of all the dedications that have been attributed to seats

**Comment by wjdp** [comment]
To kick this off can someone take a picture of every seat back (in a logical order and including the blank ones) and stick in in a SM album?

**Comment by BenWoodford76** [comment]
@wjdp I shall over the next few days

**Comment by wjdp** [comment]
Ta very much

**Comment by BenWoodford76** [comment]
this has been done :)

**Comment by wjdp** [comment]
Where be these pictures?

**Comment by BenWoodford76** [comment]
http://photos.newtheatre.org.uk/History-Project/Seats/n-QskDKs/

**Comment by wjdp** [comment]
Fantastic!

**Comment by wjdp** [comment]
Righty ho, can someone make a branch (seats sound like an apt name) with a file: `_data/seats.yaml` with items in the following format:

```yaml
- row: Z
  seat: 3
  person: Fred Bloggs
  message: |
    Fred Bloggs (Frogs)
    Did lots of theatre
    Got a third
    (bants)
- row: Z
  seat: 4
  …
```

We only set person for those with existing person records. If we think they should have person records we create blank ones.

**Comment by wjdp** [comment]
Page may want some blurb, see http://blogs.nottingham.ac.uk/newsroom/2013/11/14/bbcs-matthew-bannister-launches-new-theatre-appeal/

**Comment by BenWoodford76** [comment]
I shall have a look at this when I'm bored :)

**Comment by BenWoodford76** [comment]
@wjdp are we setting 'person:false' or just leaving the person line out?

**Comment by wjdp** [comment]
@BenWoodford76 Leave out, that line is only needed on shows as we generate person records from cast/crew lists. On the seats page we will link to people only if a page already exists.

**Comment by BenWoodford76** [comment]
@wjdp Cool, I shall do the mindless data input bit on a branch then let someone else do the proper coding ;)

**Comment by wjdp** [comment]
Fabulous 🎉

**Comment by BenWoodford76** [comment]
Have done all the individual seat info in _data/seats.yaml. Shall look tomorrow at writing a small bit about how the naming thing began as per the link above. @wjdp do we want this in the same file?

**Comment by wjdp** [comment]
@BenWoodford76 Nah, wants to be the content file that we will render the seats data in. Probs _content/seats.html

**Comment by samozzy** [comment]
Is there anything in here still to do? The seats and dedications are now [displayed quite nicely](https://history.newtheatre.org.uk/seats/).
