### ISSUE TITLE
Theo James info

### ISSUE THREAD

**Issue by nhyty** [newtheatre/history-project#848]
https://books.google.co.uk/books?id=Nh_9AgAAQBAJ&pg=PT22&lpg=PT22&dq=nottingham+new+theatre+2004&source=bl&ots=ZMl2qVzzSi&sig=6bD3TeiUo_K8Ap66cepnlyoDoWU&hl=en&sa=X&ved=0ahUKEwjBoPKMjp_UAhWDL8AKHYBTBHYQ6AEIQDAF#v=onepage&q=nottingham%20new%20theatre%202004&f=false

**Comment by BenWoodford76** [comment]
Have added all I can find in the book

**Comment by nhyty** [comment]
Bored Ben is best Ben 😄
