### ISSUE TITLE
Newspaper reviews

### ISSUE THREAD

**Issue by nhyty** [newtheatre/history-project#865]
Adding http://photos.newtheatre.org.uk/History-Project/Newspaper-Clippings/n-wTWc5F/ to the shows, from #849

**Comment by BenWoodford76** [comment]
Where do I find the image keys for them?

**Comment by wjdp** [comment]
`ImageKey` under each item on here: https://api.smugmug.com/api/v2/album/ds5Sx8!images

**Comment by BenWoodford76** [comment]
what do I put the type down as?

**Comment by BenWoodford76** [comment]
@wjdp is there a 'Newspaper' image type??

**Comment by wjdp** [comment]
@BenWoodford76 Nah, but I just use newspaper, its not strict I don't think
