### ISSUE TITLE
No author in show list for 'devised by'

### ISSUE THREAD

**Issue by samozzy** [newtheatre/history-project#870]
![history_devised_list](https://user-images.githubusercontent.com/15388319/27091688-cd88eb9a-5058-11e7-892d-f8607c623a3b.png)
'Potential' and 'Crystal Quest' don't have a 'by'. Is this a bug or a feature?

**Comment by wjdp** [comment]
Is current expected behaviour, see https://github.com/newtheatre/history-project/blob/master/_plugins/show.rb#L29
