### ISSUE TITLE
Stuff 2017

### ISSUE THREAD

**Issue by samozzy** [newtheatre/history-project#873]
- [x] Strangers
- [x] Wrecked
- [x] The Weird and the Eerie
- [x] Improvabunga
- [x] Debris
- [x] An Evening of Performance Art
- [x] Speechless
- [x] Escape for Dummies
- [x] Twenty-Something
- [x] Footnotes
- [x] The Fall of Byron Montrose: Poet, Gentleman, Lover
- [x] The Iconoclasts
- [x] Stuff Your Face With Poetry

**Comment by samozzy** [comment]
@nhyty Are we waiting on team publicity to upload their photos to SM before pushing this to master?
Do you have higher res than Facebook resolution for show posters?

**Comment by nhyty** [comment]
I've gotten the best quality posters we have already uploaded, some are just potato quality. I will push this before photos probably as they will need sorting by myself

**Comment by samozzy** [comment]
Do we want the info from the artist from [here](https://www.facebook.com/events/1712987518998453/)? If so, where?

**Comment by BenWoodford76** [comment]
> Do we want this year's StuFF poster to be the poster for shows without one? (Performance Art, Poetry)

I'd say yes

**Comment by samozzy** [comment]
Ok, it's not currently on SM so needs putting there. It's just those two shows that need it.

**Comment by BenWoodford76** [comment]
@samozzy @nhyty any idea where this can be found??

**Comment by samozzy** [comment]
@BenWoodford76 The profile picture of fb.me/stuffnotts is square, so we could use the lineup photo (portrait) instead. https://scontent-lht6-1.xx.fbcdn.net/v/t1.0-9/19420574_2303198806571191_334339820701577497_n.jpg?oh=51bcc8fd78488852f2951f1d697ba4b4&oe=59DD5ABE

**Comment by samozzy** [comment]
@BenWoodford76 wrt Stuff poster as show photo, we should probably then fill in the gaps for Stuff 2015 using that poster, as there are many without a photo there.

**Comment by nhyty** [comment]
i agree

**Comment by BenWoodford76** [comment]
@nhyty I also agree

**Comment by samozzy** [comment]
Cool. I'll make that happen tonight.
Am also putting in Impact's reviews tonight.
