### ISSUE TITLE
Markdown in Reviews

### ISSUE THREAD

**Issue by samozzy** [newtheatre/history-project#879]
Is possible, but changes the styling of the font, as it makes it into a paragraph. Would be nice to adhere to the source's formatting and italicise show names without html.

**Comment by wjdp** [comment]
Personally I'd like to keep this field as simple as possible. Adding formatting to text that could be shown anywhere on the site—for potentially minimal gain—is a bit much for me.

**Comment by wjdp** [comment]
Closing this for now
