### ISSUE TITLE
Separation of In House and Fringe/UNCUT?

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#88]
![image](https://cloud.githubusercontent.com/assets/1690934/7843259/6323f336-04a0-11e5-82ca-5cb372d7d260.png)

Currently in house and fringe are in the same list, should they be separate?

Personally I quite like them in the same list, I will add a 'In house/fringe' label to the show items though.

**Comment by wjdp** [comment]
@phgeller ?

**Comment by phgeller** [comment]
I agree that they should be in the same list. Maybe just have a little
icon/notation for fringe shows?

*------------------*
*Philip Geller*

*M: 07754 056896*
*E:  Philip.Geller@gmail.com <Philip.Geller@gmail.com>*
*W: www.philgeller.co.uk <http://www.philgeller.co.uk>*

**Comment by wjdp** [comment]
Yep mu thoughts exactly, will do this soon
