### ISSUE TITLE
Use the Travis cronjob build to do boring things

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#884]
We have a daily build, it doesn't matter how long it takes. We can use it to do boring things like:

- [x] SmugMug cache updates
- [ ] More in-depth HTML proofing
- [ ] ??? @newtheatre/editors ideas?

**Comment by nhyty** [comment]
These sound sensible

**Comment by wjdp** [comment]
Can't think of any more HTML proofing without being rate limited. So closing for now. SM done.
