### ISSUE TITLE
cast_short and crew_short attributes

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#90]
The missing / short detection is very arbitrary - list is 0 or <= 2. Should have a switch for keeping the short message up, and another for customising the text shown - "We know there are 4 more cast members but have no idea who they are".

**Comment by wjdp** [comment]
```
cast: ...
cast_short: true
cast_short_message: "We know there are 4 more cast members but have no idea who they are."
```

**Comment by BenWoodford76** [comment]
is this potentially another project for @samozzy ??

**Comment by samozzy** [comment]
Did you make any headway with this, @wjdp? I can give it a stab over the next few days.

**Comment by wjdp** [comment]
Nope, please stab
