### ISSUE TITLE
Grab Trivia Points from Interviews

### ISSUE THREAD

**Issue by BenWoodford76** [newtheatre/history-project#903]
Interviews for stories

- [x]  http://www.impactnottingham.com/2014/11/nottingham-new-theatre-interview-doubt/
- [x]  http://www.impactnottingham.com/2014/11/nottingham-new-theatre-interview-bent/
- [x]  http://www.impactnottingham.com/2014/11/nottingham-fringe-interview-infirmity/
- [x]  http://www.impactnottingham.com/2014/11/nottingham-new-theatre-interview-our-countrys-good/
- [x]  http://www.impactnottingham.com/2014/12/nnt-fringe-season-interview-the-adventure-of-anne-marie-du-bourbon/
- [x]  http://www.impactnottingham.com/2014/12/nnt-interview-king-lear/

**Comment by wjdp** [comment]
We should archive and link to these articles (with `type: Article` rather than `Review`)
