### ISSUE TITLE
Student Page Issues

### ISSUE THREAD

**Issue by samozzy** [newtheatre/history-project#929]
## Then/Now
It appears that if a degree is present on a person page, then they get the Then/Now columns.
If this person is a student, the degree is still Now.

Options:
- Only include the degree once they have actually got it.
- Logically decide when to display the Then/Now columns based on student status.
??? 

## Bio submissions
Still reads as "we are accepting biographies on New Theatre alumni" - students are not alumni.

**Comment by wjdp** [comment]
Yeah, built this with the assumption that people only get bios once they are alumni. This should be fixed.
