### ISSUE TITLE
Mobile search

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#94]
Currently search page works on mobile, there just isn't a link to it, add one top right probs.

Extends #31

**Comment by nhyty** [comment]
![picture 1](https://cloud.githubusercontent.com/assets/14825903/10774085/18614a7c-7cf7-11e5-9916-66d973a70f64.jpg)
 My suggestion would be in the top bar, next to the NNT logo, to expand a search bar upon pressing

**Comment by nhyty** [comment]
bump

**Comment by wjdp** [comment]
:unamused: effort, will try
