### ISSUE TITLE
Prose defaults to unpublished, Jekyll3 pays attention to this

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#96]
Make prose default published

**Comment by phgeller** [comment]
Yes please! Really annoying!


*------------------*
*Philip Geller*

*M: 07754 056896*
*E:  Philip.Geller@gmail.com <Philip.Geller@gmail.com>*
*W: www.philgeller.co.uk <http://www.philgeller.co.uk>*

**Comment by wjdp** [comment]
https://github.com/prose/prose/wiki/Prose-Configuration

**Comment by wjdp** [comment]
Should now work

![image](https://cloud.githubusercontent.com/assets/1690934/7898486/a33b2e84-06f9-11e5-8bbb-5b7d686897ae.png)
