### ISSUE TITLE
Inconsistent metadata WRT show titles

### ISSUE THREAD

**Issue by GingertronMk1** [newtheatre/history-project#966]
Some shows (it's about a 50:50 split) have their titles delimited by quote marks whereas others don't. I was wondering if there's a specific reason for this?

**Comment by wjdp** [comment]
Can you give a few examples?

**Comment by GingertronMk1** [comment]
From *A Beautiful Thing*:
`title: A Beautiful Thing`

From *Escape For Dummies*
`title: "Escape for Dummies"`

That's just within 16_17, it is as I say about an even split between all of them

**Comment by wjdp** [comment]
Ah gotcha, it all renders out to the same thing. You need to wrap the string in quotes if special characters are used (e.g. `'` single quotes), but can omit them for simple strings. 

Basically it doesn't really matter. If you're interested have a look at the docs for the YAML format. Generally I've found it to be a very clean way of marking up the meta data but there is the odd rough corner to it.

:smile:
