### ISSUE TITLE
Over There - Broken

### ISSUE THREAD

**Issue by johnathan99j** [newtheatre/history-project#986]
#982 Very much doesn't work

![image](https://user-images.githubusercontent.com/15066398/32449384-4d61ef24-c309-11e7-9609-59e6a6093d75.png)

![image](https://user-images.githubusercontent.com/15066398/32449364-435ce330-c309-11e7-9c8e-ac677c7152df.png)

**Comment by wjdp** [comment]
The frontmatter isn't valid YAML

use http://www.yamllint.com/

**Comment by nhyty** [comment]
@wjdp Will fix.

**Comment by BenWoodford76** [comment]
Just for the less code literate of us, when it's fixed can you tell me what invalidated the YAML?

**Comment by nhyty** [comment]
@BenWoodford76 I can't see anything obvious...

**Comment by BenWoodford76** [comment]
![image](https://user-images.githubusercontent.com/18663231/32453736-06992f9c-c315-11e7-9894-95582425be82.png)

**Comment by BenWoodford76** [comment]
extra spaces in the cast and crew lists, will fix now

**Comment by BenWoodford76** [comment]
if someone can review #988 so I can merge that would be fabulous
