### ISSUE TITLE
History Project logo looks icky now

### ISSUE THREAD

**Issue by nhyty** [newtheatre/history-project#991]
![capture](https://user-images.githubusercontent.com/14825903/32682813-1362562e-c66f-11e7-8913-c474208a7c03.PNG)

**Comment by nhyty** [comment]
@wjdp how easy could i fix this???

**Comment by wjdp** [comment]
@newtheatre/history-project If people have five mins can they have a look at this in their various browsers while resizing the window?

(should look good from all the way small to all the way big)

**Comment by nhyty** [comment]
I did this yesterday and it all looks good to me

**Comment by wjdp** [comment]
Closing, re-open if we find any more ickyness
